apps/board/urls.py
from rest_framework.routers import DefaultRouter

from . import views


router = DefaultRouter(trailing_slash=False)
router.register(r'sprints', views.SprintViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'users', views.UserViewSet)

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework.authtoken.views import obtain_auth_token

from apps.board.urls import router
from apps.board import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(router.urls)),
    url(r'^$', views.Index.as_view(), name='index'),
]

apps/board/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy

from model_utils import Choices


class Sprint(models.Model):
    name = models.CharField('name', max_length=100, blank=True, default='')
    description = models.TextField('description', blank=True, default='')
    end = models.DateField('end', unique=True)

    def __str__(self):
        return self.name or ugettext_lazy(f'Spring ending {self.end}')


class Task(models.Model):
    STATUS = Choices(
        (1, 'TODO', ugettext_lazy('Not Started')),
        (2, 'IN_PROGRESS', ugettext_lazy('In Progress')),
        (3, 'TESTING', ugettext_lazy('Testing')),
        (4, 'DONE', ugettext_lazy('Done')),
    )
    name = models.CharField('name', max_length=100)
    description = models.TextField('description', blank=True, default='')
    sprint = models.ForeignKey(
        'Sprint',
        blank=True,
        default='',
        verbose_name='sprint'
    )
    status = models.SmallIntegerField(
        'status',
        choices=STATUS,
        default=STATUS.TODO
    )
    order = models.SmallIntegerField('order', default=0)
    assigned = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        verbose_name='assigned'
    )
    started = models.DateField('started', blank=True, null=True)
    due = models.DateField('due', blank=True, null=True)
    completed = models.DateField('completed', blank=True, null=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

apps/board/forms.py
import django_filters

from django.contrib.auth import get_user_model

from . import models


User = get_user_model()


class NullFilter(django_filters.BooleanFilter):

    def filter(self, qs, value):
        if value is not None:
            return qs.filter(**{f'{self.name}__isnull': value})
        return qs


class SprintTask(django_filters.FilterSet):
    end_min = django_filters.DateFilter(name='end', lookup_expr='gte')
    end_max = django_filters.DateFilter(name='end', lookup_expr='lte')

    class Meta:
        model = models.Sprint
        fields = ('end_min', 'end_max', )


class TaskFilter(django_filters.FilterSet):
    backlog = NullFilter(name='sprint')

    class Meta:
        model = models.Task
        fields = ('sprint', 'status', 'assigned', 'backlog', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filters['assigned'].extra.update(
            {'to_field_name': User.USERNAME_FIELD}
        )

apps/board/views.py
import hashlib

import requests

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.signing import TimestampSigner
from django.views import generic

from rest_framework import authentication, filters, permissions, viewsets
from rest_framework.renderers import JSONRenderer

from . import forms, models, serializers

User = get_user_model()


class Index(generic.TemplateView):
    template_name = 'board/index.html'


class UpdateHookMixin:

    def _build_hook_url(self, obj):
        if isinstance(obj, User):
            model = 'user'
        else:
            model = obj.__class__.__name__.lower()

        protocol = 'https' if settings.WATERCOOLER_SECURE else 'http'
        server = settings.WATERCOOLER_SERVER

        return f'{protocol}://{server}/{model}/{obj.pk}'

    def _send_hook_request(self, obj, method):
        url = self._build_hook_url(obj)
        if method in ('POST', 'PUT', ):
            serializer = self.get_serializer(obj)
            renderer = JSONRenderer()
            context = {'request': self.request}
            body = renderer.render(serializer.data, renderer_context=context)
        else:
            body = None

        headers = {
            'content-type': 'application/json',
            'X-Signature': self._build_hook_signature(method, url, body),
        }

        try:
            response = requests.request(
                method,
                url,
                data=body,
                timeout=0.5,
                headers=headers
            )
            response.raise_for_status()
        except requests.exceptions.ConnectionError:
            pass
        except requests.exceptions.Timeout:
            pass
        except requests.exceptions.RequestException:
            pass

    def _build_hook_signature(self, method, url, body):
        signer = TimestampSigner(settings.WATERCOOLER_SECRET_KEY)
        method = method.lower()
        body = hashlib.sha256(body or b'').hexdigest()
        value = f'{method}:{url}:{body}'
        return signer.sign(value)

    def post_save(self, obj, create=False):
        method = 'POST' if create else 'PUT'
        self._send_hook_request(obj, method)

    def pre_delete(self, obj):
        self._send_hook_request(obj, 'DELETE')


class SprintViewSet(UpdateHookMixin, viewsets.ModelViewSet):
    queryset = models.Sprint.objects.order_by('end')
    serializer_class = serializers.SprintSerializer
    filter_class = forms.SprintTask
    search_fields = ('name', )
    ordering_fields = ('end', 'description', )


class TaskViewSet(UpdateHookMixin, viewsets.ModelViewSet):
    queryset = models.Task.objects.all()
    serializer_class = serializers.TaskSerializer
    filter_class = forms.TaskFilter
    search_fields = ('name', 'description', )
    ordering_fields = ('name', 'order', 'started', 'due', 'completed', )


class UserViewSet(UpdateHookMixin, viewsets.ReadOnlyModelViewSet):
    lookup_field = User.USERNAME_FIELD
    lookup_url_kwarg = User.USERNAME_FIELD
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = serializers.UserSerializer
    search_fields = (User.USERNAME_FIELD, )

apps/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Scrum Board</title>

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/board.css' %}">

    <script type="text/html" id="home-template">
        <h1>Your Sprints</h1>
        <button class="add" type="submit">Add Sprint</button>
        <% if (sprints !== null) { %>
            <div class="sprints">
                <% _.each(sprints.models, function (sprint) { %>
                    <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
                        <%- sprint.get('name') %> <br/>
                        <span>DUE BY <%- sprint.get('end') %></span>
                    </a>
                <% }) %>
            </div>
        <% } else { %>
            <h3 class="loading">Loading...</h3>
        <% } %>
    </script>

    <script type="text/html" id="login-template">
        <form action="" method="POST">
            <label for="id_username">Username</label>
            <input id="id_username" type="text" name="username" maxlength="30" required/>
            <label for="id_password">Password</label>
            <input id="id_password" type="password" name="password" required/>
            <button type="submit">Login</button>
        </form>
    </script>

    <script type="text/html" id="header-template">
        <span class="title">
            <a href="/">Scrum Board Example</a>
        </span>
        <% if (authenticated) { %>
            <nav>
                <a href="/" class="button">Your Sprints</a>
                <a href="#" class="logout button">Logout</a>
            </nav>
        <% } %>
    </script>

    <script type="text/html" id="new-sprint-template">
        <form action="" method="POST">
            <label for="id_name">Sprint Name</label>
            <input id="id_name" type="text" name="name" maxlength="100" required>
            <label for="id_end">End Date</label>
            <input id="id_end" type="date" name="end">
            <label for="id_description">Description</label>
            <textarea id="id_description" name="description" cols="50"></textarea>
            <button class="cancel">Cancel</button>
            <button type="submit">Create</button>
        </form>
    </script>

    <script type="text/html" id="sprint-template">
        <% if (sprint !== null) { %>
            <% if (!sprint.invalid) { %>
                <h2><%- sprint.get('name') %></h2>
                <span class="due-date">Due <%- sprint.get('end') %></span>
                <p class="description"><%- sprint.get('description') %></p>
                <div class="tasks"></div>
            <% } else { %>
                <h1>Sprint <%- sprint.get('id') %> not found</h1>
            <% } %>
        <% } else { %>
            <h1 class="loading">Loading...</h1>
        <% } %>
    </script>

    <script type="text/html" id="status-template">
        <h4><%- title %></h4>
        <div class="list"></div>
        <% if (sprint === null) { %>
            <button class="add" type="submit">Add Task</button>
        <% } %>
    </script>

    <script type="text/html" id="new-task-template">
        <form class="add-task" action="" method="POST">
            <label for="id_name">Task Name</label>
            <input id="id_name" type="text" name="name" maxlength="100" required>
            <label for="id_description">Description</label>
            <textarea id="id_description" name="description"></textarea>
            <button class="create" type="submit">Create</button>
            <button class="cancel" type="submit">Cancel</button>
        </form>
    </script>

    <script type="text/html" id="task-item-template">
        <%- task.get("name") %>
    </script>

    <script type="text/html" id="task-detail-template">
        <div data-field="name" class="name" contenteditable="true">
            <%- task.get('name') %>
        </div>
        <div data-field="description" class="description" contenteditable="true">
            <%- task.get('description') %>
        </div>
        <div class="with-label">
            <div class="label">Due:</div>
            <div data-field="due" class="due data" contenteditable="true">
                <%- task.get('due') || empty %>
            </div>
        </div>
        <div class="with-label">
            <div class="label">Assigned To:</div>
            <div data-field="assigned" class="assigned" contenteditable="true">
                <%- task.get('assigned') || empty %>
            </div>
        </div>
        <form>
            <button class="cancel" type="submit">Close</button>
            <button class="save hide" type="submit">Save</button>
        </form>
    </script>
</head>
<body>

    <div id="content"></div>

    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'underscore/underscore.js' %}"></script>
    <script src="{% static 'backbone/backbone.js' %}"></script>

    <script id="config" type="text/json">
        {
            "models": {},
            "collections": {},
            "session": null,
            "views": {},
            "router": null,
            "apiRoot": "{% url 'api-root' %}",
            "apiLogin": "{% url 'api-token' %}"
        }
    </script>
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/socket.js' %}"></script>
    <script src="{% static 'js/models.js' %}"></script>
    <script src="{% static 'js/views.js' %}"></script>
    <script src="{% static 'js/router.js' %}"></script>
</body>
</html>